# Generated by Django 4.2.30 on 2026-06-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('historical_review', models.TextField(help_text='Breve reseña histórica de la danza')),
                ('map_image', models.CharField(help_text='Ruta estática para el mapa del país, por ejemplo danceapp/images/argentina-map.svg', max_length=255)),
                ('collage_images', models.JSONField(default=list, help_text='Lista de rutas a imágenes estáticas para el collage de la danza')),
                ('video_url', models.URLField(blank=True, help_text='URL del video embebido de la danza')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
